apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.pvc.name }}
spec:
  storageClassName: {{ .Values.mongodb.storageClass.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.pvc.size }}
