apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.deployment.name }}
  namespace: default
  labels:
    app: {{ .Values.mongodb.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongodb.appName }}
  replicas: {{ .Values.mongodb.deployment.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.appName }}
    spec:
      containers:
      - name: {{ .Values.mongodb.deployment.name }}
        image: mongo:latest
        ports:
            - containerPort: 27017
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts:
          - name: data
            mountPath: /data/db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.mongodb.pvc.name }}

