apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.mongodb.storageClass.name }}
provisioner: {{ .Values.mongodb.storageClass.provisioner }}
volumeBindingMode: WaitForFirstConsumer
