apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: default
spec:
  selector:
    app: {{ .Values.mongodb.appName }}
  ports:
  - name: mongodb-service
    protocol: TCP
    port: {{ .Values.mongodb.deployment.port }}
    targetPort: 27017
