services:
  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - db-data:/data/db
    networks:
      - network-backend

  backend:
    build: ./backend
    ports:
      - 3001:3001
    networks:
      - network-backend
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - network-backend
    depends_on:
      - backend 

volumes:
  db-data:
    driver: local

networks:
  network-backend:
    driver: bridge

