# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springmusic-deployment
  namespace: default
  labels:
    app: springmusic
spec:
  selector:
    matchLabels:
      app: springmusic
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  springmusic
      labels:
        app: springmusic
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - image: zudin116/spring-music:latest
        name: spring-music
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: spring-music
---

apiVersion: v1
kind: Service
metadata:
  name: springmusic-service
  namespace: default
spec:
  selector:
    app: springmusic
  type: NodePort
  ports:
  - name: springmusic-service
    protocol: TCP
    port: 8080
    targetPort: 8080

