version: '3'


services: 
  mongodb:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db
      - configdb-data:/data/configdb
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo-network
    depends_on:
      - mongodb


volumes:
  db-data:
    driver: local

  configdb-data:
    driver: local


networks:
  mongo-network:
    driver: bridge
