apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: minikube-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: default
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
            - containerPort: 27017
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
            readOnly: true
          - name: data
            mountPath: /data/db
      volumes:
      - name: secret-volume
        secret:
          secretName: mongodb-secret
      - name: data
        persistentVolumeClaim:
          claimName: mongodb-pvc

        # livenessProbe:
        #   tcpSocket:
        #     port: 27017
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   tcpSocket:
        #     port: 27017
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: default
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-service
    protocol: TCP
    port: 27017
    targetPort: 27017
---

