apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-fix
spec:
  capacity:
    storage: 1Gi
  storageClassName: minikube-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
