services:
  elasticsearch:
    image: elasticsearch:7.17.25
    environment:
      discovery.type: single-node
    networks:
      - elasticsearch-neywork
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data/

  kibana:
    image: kibana:7.17.25
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elasticsearch-neywork
    ports: 
      - 5601:5601
    depends_on: 
      - elasticsearch

  logstash:
    image: logstash:7.17.25
    volumes:
      - ./logstash_config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      ELASTIC_HOSTS: http://elasticsearch:9200
    networks:
      - elasticsearch-neywork
    depends_on:
      - elasticsearch
    

volumes:
  elasticsearch-data:
    driver: local


networks:
  elasticsearch-neywork:
    driver: bridge

