version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
