version: "3.8"

services:
  mongo1:
    image: mongo
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - 27017:27017
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    networks:
      - mongoCluster

  mongo2:
    image: mongo
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27018" ]
    ports:
      - 27018:27018
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
    networks:
      - mongoCluster

  mongo3:
    image: mongo
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27019" ]
    ports:
      - 27019:27019
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
    networks:
      - mongoCluster

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo1,mongo2,mongo3/?replicaSet=rs0
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongoCluster
    depends_on:
      - mongo1
      - mongo2
      - mongo3

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:


networks:
  mongoCluster:
